name: "Send Slack Notification"
description: "Sends a notification to Slack about a PR"
inputs:
  slack-token:
    description: "Slack Bot Token"
    required: true
  channel:
    description: "Slack channel to send message to"
    required: true
  thread-ts:
    description: "Thread timestamp to reply to"
    required: false
  pr-title:
    description: "Pull request title"
    required: true
  pr-url:
    description: "Pull request URL"
    required: true
  pr-body:
    description: "Pull request body"
    required: true
  repository:
    description: "Repository name"
    required: true
  author:
    description: "PR author"
    required: true
  is-update:
    description: "Whether this is an update message"
    required: true
    default: "false"

outputs:
  response:
    description: "Response from Slack API"
    value: ${{ steps.slack-notification.outputs.response }}

runs:
  using: "composite"
  steps:
    - name: Send to Slack
      id: slack-notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-token }}
        payload: |
          {
            "channel": "#${{ inputs.channel }}",
            "text": "${{ inputs.is-update == 'true' && 'PR Update' || 'New PR Notification' }}",
            ${{ inputs.thread-ts != '' && format('"thread_ts": "{0}",', inputs.thread-ts) || '' }}
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🔍 Pull Request",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*<${{ inputs.pr-url }}|${{ inputs.pr-title }}>*\n*Repository:* ${{ inputs.repository }}\n*Author:* ${{ inputs.author }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.pr-body }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-token }}
